# Worksheet 04

Name: Haotian Shangguan
UID: 

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

In the minkowski distance, the parameter d means the dimension and parameter p means Euclidean Distance when p = 1 and manhattan Distance when p = 1. 

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Manhattan Distance allows you to find the shortest distance between two points without follows any rules but Euclidean distance has a specific rule you need to follow. 

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The distance will be one when p is very large.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

When p < 1, that means 1/p > 1. At this case, it will violates the triangle inequality which d(B, C) > d(B, A) + d(A, C)

e) when would you use cosine similarity over the euclidan distance?

When directionmatters more than magnitude. 

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard distance accounts for the similarity in terms of presence or absence of characteristics without considering their magnitude, which Manhattan distance directly measures through the sum of absolute differences across dimensions.

#### Part 2

Consider the following two sentences:

In [2]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [3]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [4]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'Bob', 'is', 'my', 'Alice', 'name']
[1, 0, 1, 1, 1, 1]


Let's add a new sentence to our corpus:

In [5]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [6]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hi', 'hello', 'Bob', 'is', 'Claude', 'my', 'Alice', 'name']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [7]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 1, 0, 1, 0, 1, 1, 1]
[0, 1, 1, 1, 0, 1, 0, 1]
[1, 0, 0, 1, 1, 1, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [20]:
#Manhattan distance
def Manhattan_D(v1, v2): 
    sum = 0
    for i in range(len(v1)): 
        sum += abs(v1[i] - v2[i])
        
    return sum

print("v1 and v2: ", Manhattan_D(v1, v2))
print("v1 and v3: ", Manhattan_D(v1, v3))
print("v2 and v3: ", Manhattan_D(v2, v3))

v1 and v2:  2
v1 and v3:  4
v2 and v3:  4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [1]:
corpus = ["hi Alice", "hello Claude", "Bob my name is Claude", "hi Claude my name is Alice", "hello Bob"]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

v_matrix = [[1 if x in s else 0 for x in all_words] for s in corpus]
for i in range(len(v_matrix)): 
    print(v_matrix[i])

['my', 'hello', 'Bob', 'name', 'Claude', 'hi', 'Alice', 'is']
[0, 0, 0, 0, 0, 1, 1, 0]
[0, 1, 0, 0, 1, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 1]
[1, 0, 0, 1, 1, 1, 1, 1]
[0, 1, 1, 0, 0, 0, 0, 0]


e) How many rows and columns does this matrix have?

In [30]:
print("row: ", len(v_matrix), "Col: ", len(v_matrix[0]))

row:  5 Col:  8


f) When using the Manhattan distance, which two sentences are the most similar?

In [38]:
minimum = Manhattan_D(v_matrix[0], v_matrix[1])
vector = (0, 0)
for i in range(len(v_matrix)): 
    for j in range(i + 1, len(v_matrix)): 
        if minimum > Manhattan_D(v_matrix[i], v_matrix[j]): 
            minimum = Manhattan_D(v_matrix[i], v_matrix[j])
            vector = (i, j)

print("Two sentences are the most similar is: ", vector)
print("The distance between them is: ", minimum)

Two sentences are the most similar is:  (1, 4)
The distance between them is:  2


#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [2]:
import numpy as np

def Pairwise_Distance(graph): 
    result = np.zeros((len(graph), len(graph)))
    
    for i in range(len(graph)): 
        for j in range(len(graph)): 
            if i == j: 
                result[i][j] = 0
            
            result[i][j] = np.sum(np.abs(graph[i] - graph[j]))
    return result

graph1 = np.array([
    [0, 1, 0, 0],
    [1, 0, 1, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0]
])

graph2 = np.array([
    [0, 1, 0, 1],
    [1, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 1, 0, 0]
])

graph3 = np.array([
    [0, 0, 1, 0],
    [0, 0, 1, 0],
    [1, 1, 0, 1],
    [0, 0, 1, 0]
])

# Calculate distances
graphs = [graph1, graph2, graph3]
print(Pairwise_Distance(graphs))




[[ 0.  6.  4.]
 [ 6.  0. 10.]
 [ 4. 10.  0.]]
